name: Release Notes drafter (release-please)
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.MUSIC_ASSISTANT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.MUSIC_ASSISTANT_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
      - name: Validate GitHub App installation
        env:
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
          INSTALLATION_ID: ${{ steps.app-token.outputs.installation-id }}
        run: |-
          test "$APP_SLUG" = "musicassistant-bot"
          test "$INSTALLATION_ID" = "146062122"
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: simple
          manifest-file: .github/workflows/.release-please-manifest.json
          config-file: .github/workflows/.release-please-config.json
